### ISSUE TITLE
How tasks design are licensed?

### ISSUE THREAD

**Issue by ghost** [wood-galaxy/mooc-workbench#1]
I want reproduce each task design using other software (SolveSpace, LibreCAD, Blender, etc.), but how should I license resulted files?

![pic.1](https://pbs.twimg.com/media/ELYSL0OXkAE-Jt0.png:large)

I would use only dimensions from each design instructions

- https://github.com/j-wiedemann/mooc-workbench/tree/master/medias/instructions

But inside each PDF no any info about design licensing, so could I license own files based only on design of each task under Creative Commons `CC-0` or `CC-BY-SA 4.0` license, or how figure out?

**Comment by j-wiedemann** [comment]
Hi, thanks for your interest. 
I don't have the answer right now and will ask this to the team.
According to the information about the mooc associated with this project : https://www.fun-mooc.fr/courses/course-v1:MinesTelecom+04036+session01/about
licences should be at least CC-BY-NC
![image](https://user-images.githubusercontent.com/4691535/71198095-5502b880-2293-11ea-8778-0f36f4af8775.png)
I will come back when I have answers.

**Comment by j-wiedemann** [comment]
There is now a file in medias/instructions
https://github.com/j-wiedemann/mooc-workbench/blob/935db7b4bea91412f0fef83ee4a15f04120b0a8a/medias/instructions/licence
that specifies the license : CC-BY-SA-NC
